import { getStore } from './store';

// export const ActionTypes = {
// 	ADD_DRIVER_POLICY_CHANGE : 'ADD_DRIVER_POLICY_CHANGE', // add new driver 
// 	ADD_VEHICLE_POLICY_CHANGE : 'ADD_VEHICLE_POLICY_CHANGE',
// 	CANCEL_ADDED_DRIVER_POLICY_CHANGE : 'CANCEL_ADDED_DRIVER_POLICY_CHANGE', //remove newly added driver
// 	CANCEL_ADDED_VEHICLE_POLICY_CHANGE : 'CANCEL_ADDED_VEHICLE_POLICY_CHANGE', //remove newly added vehicle
// 	CANCEL_ALL_POLICY_CHANGE : 'CANCEL_ALL_POLICY_CHANGE', // cancel all the newly added changes
// 	CANCEL_EDIT_DRIVER_POLICY_CHANGE : 'CANCEL_EDIT_DRIVER_POLICY_CHANGE',
// 	CANCEL_EDIT_VEHICLE_POLICY_CHANGE : 'CANCEL_EDIT_VEHICLE_POLICY_CHANGE',
// 	CANCEL_REMOVE_DRIVER_POLICY_CHANGE : 'CANCEL_REMOVE_DRIVER_POLICY_CHANGE',
// 	CANCEL_REMOVE_VEHICLE_POLICY_CHANGE : 'CANCEL_REMOVE_VEHICLE_POLICY_CHANGE',
// 	EDIT_DRIVER_POLICY_CHANGE : 'EDIT_DRIVER_POLICY_CHANGE', // edit existing driver
// 	EDIT_VEHICLE_POLICY_CHANGE : 'EDIT_VEHICLE_POLICY_CHANGE', // edit existing vehicle
// 	HIDE_ERROR: 'HIDE_ERROR',
// 	REMOVE_DRIVER_POLICY_CHANGE : 'REMOVE_DRIVER_POLICY_CHANGE', // remove existing driver
// 	REMOVE_VEHICLE_POLICY_CHANGE : 'REMOVE_VEHICLE_POLICY_CHANGE', // remove existing vehicle
// 	SHOW_ERROR: 'SHOW_ERROR',
// };

// export function addVehiclePolicyChange(change) {
// 	return getStore().dispatch({
// 		type : ActionTypes.ADD_VEHICLE_POLICY_CHANGE,
// 		change
// 	});
// }
